#2839 [DigiriskDocuments] add: formconfirm when delete file
Evarisk/Digirisk pull request #3146
Opened 2023-05-26 08:55 UTC by evarisk-micka

2023-06-12 18:30 UTC, nicolas-eoxia requested changes
Dans l'ensemble ça marche cependant il faut appliquer les changements et garder une cohérence 

De plus, il manque certain fichier comme la génération du ticket document/prévention document et fire permit document

2023-06-12 18:30 UTC, nicolas-eoxia commented on view/digiriskelement/digiriskelement_card.php
> +
Ce code ne doit pas être placer la il faut qu'il soit dans l'action view de la card 

Inutile d'appeler digiriskformconfirm faire appel à la fonction standard formconfirm

Dans formconfirm bien regarder les paramètres il en manque certain dans l'utilisation de digiriskformconfirm

2023-06-12 18:30 UTC, nicolas-eoxia commented on langs/fr_FR/digiriskdolibarr.lang
> +ConfirmDeleteFile = Êtes-vous sûr de vouloir <b>supprimer ce fichier</b> ? <br> Une fois supprimé ce fichier ne sera <b>plus accessible ni récupérable d'aucune façon</b>.
Il me semble que ces trad existent déjà dans dolibarr

2024-06-07 10:29 UTC, evarisk-micka commented
A faire dans saturne

2024-06-07 10:29 UTC, closed without merging