#3682 [LegalDisplay] add: graph on legal display
Evarisk/Digirisk pull request #3689
Opened 2024-02-09 16:40 UTC by evarisk-charles

2024-02-12 09:44 UTC, nicolas-eoxia requested changes
Très bien dans l'ensemble, il y a quand même quelques imprécisions. À revoir.

2024-02-12 09:44 UTC, nicolas-eoxia commented on class/digiriskdolibarrdocuments/informationssharing.class.php
> +        $legalDisplayGraphInfos = $this->getInformationsSharingNumber();
Il faut faire attention, copier coller, problème de nom de variables

2024-02-12 09:44 UTC, nicolas-eoxia commented on class/digiriskdolibarrdocuments/informationssharing.class.php
> +        $socialResources = ['TitularsCSE', 'AlternatesCSE', 'TitularsDP', 'AlternatesDP'];
J'ai l'impression qu'il manque des valeurs ici

Comme le responsable harcèlement

2024-02-12 09:44 UTC, nicolas-eoxia commented on class/digiriskdolibarrdocuments/legaldisplay.class.php
> +        $securityResources = ['SAMU','Pompiers','Police','AllEmergencies','RightsDefender','PoisonControlCenter', 'Responsible', 'LabourDoctorSociety', 'LabourDoctorContact', 'LabourInspectorSociety'
Pareil, je crois qu'il manque des constantes

2024-02-12 09:44 UTC, nicolas-eoxia commented on langs/fr_FR/digiriskdolibarr.lang
> +InformationsSharingRate              = Taux de remplissage des informations
La trad n'est pas aligner avec les autres et pas au bon endroit surtout

2024-02-12 09:44 UTC, nicolas-eoxia commented on view/digiriskstandard/digiriskstandard_informationssharing.php
>  saturne_load_langs(['other']);
Inutile other ici

2024-02-12 09:44 UTC, nicolas-eoxia commented on view/digiriskstandard/digiriskstandard_informationssharing.php
> +if ($resHook < 0) setEventMessages($hookmanager->error, $hookmanager->errors, 'errors');
Ce n'est pas PSR-12

2024-02-12 09:44 UTC, nicolas-eoxia commented on view/digiriskstandard/digiriskstandard_informationssharing.php
Il manque pas mal de Clean code dans ce fichier

2024-02-12 09:44 UTC, nicolas-eoxia commented on view/digiriskstandard/digiriskstandard_legaldisplay.php
> +global $db, $conf, $langs, $moduleNameLowerCase, $user, $hookmanager;
Dans l'ordre alphabétique

2024-02-12 09:44 UTC, nicolas-eoxia commented on view/digiriskstandard/digiriskstandard_legaldisplay.php
> +print '<div class="fichehalfleft">';
La classe fichecenter doit encore exister dans le fichier. C'est bizarre là.

2024-02-21 10:41 UTC, evarisk-micka requested changes
Traductions:
DerogationSchedulePermanent 
DerogationScheduleOcassional 

-----


Vérifier pourquoi le tableau de bord est vide ?



-----
![image](https://github.com/Evarisk/Digirisk/assets/111346550/448e07b5-15d3-4b37-8cc1-62ac89a63d05)

2025-01-09 14:33 UTC, closed without merging