#3950 [Risk] add: move medias inside medias bloc
Evarisk/Digirisk pull request #3957
Opened 2024-06-05 13:43 UTC by evarisk-francois

2024-06-07 10:42 UTC, evarisk-micka requested changes
pense à faire la même correction dans toute les occurrences des modales d'évaluation
(comme riskassessment_view_edit_modal)

2024-06-07 10:42 UTC, evarisk-micka commented on core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
> +                            <?php if ($conf->global->DIGIRISKDOLIBARR_ADVANCED_RISKASSESSMENT_METHOD) : ?>
Quitte à modifier un peu le code, pense à remplacer le $conf->global->DIGIRISKDOLIBARR_ADVANCED_RISKASSESSMENT_METHOD 
Par getDolGlobalInt('DIGIRISKDOLIBARR_ADVANCED_RISKASSESSMENT_METHOD') > 0

2024-06-07 10:47 UTC, evarisk-micka commented
![image](https://github.com/Evarisk/Digirisk/assets/111346550/1d33d27b-4f7d-4cf9-80ca-3877da4eca46)

2024-06-07 10:49 UTC, evarisk-micka commented
Profites en dans la vue edit pour ajuster la hauteur de la modal qui dépasse sur la barre de menu en haut
Et aussi demander à Amandine des avis sur le positionnement des blocs (mettre le commentaire sous l'évaluation et le bloc média ?)

![image](https://github.com/Evarisk/Digirisk/assets/111346550/af542d69-736c-4d24-bb29-e94112e4e6a9)

2024-06-26 14:55 UTC, evarisk-francois commented
@eoxia-amandine faire aussi le css pour l'ajout d'évaluation de risque (digiriskdolibarr_riskassessment_view.tpl.php) et l'édition d'évaluation de risque (digiriskdolibarr_riskassessment_view_edit_modal.tpl.php)

2025-01-09 14:28 UTC, closed without merging