#3983 [RiskGraph] add: add position to order charts
Evarisk/Digirisk pull request #3985
Opened 2024-06-19 07:44 UTC by evarisk-francois

2024-06-19 09:35 UTC, evarisk-micka requested changes
Les positions 10 -> 20 -> 30 -> 40 etc...

2024-06-19 09:35 UTC, evarisk-micka commented on class/accident.class.php
> +
un espace en trop

2024-06-19 09:35 UTC, evarisk-micka commented on class/digiriskelement.class.php
> +
Un tab en trop au lieu d'un espace vide, pareil au dessus

2024-06-19 09:35 UTC, evarisk-micka commented on class/riskanalysis/risk.class.php
> +        $riskAssessmentList = $riskAssessment->fetchAll('', '', 0, 0, ['customsql' => 'status > 0']);
Pas besoin

2024-06-19 09:35 UTC, evarisk-micka commented on class/riskanalysis/risk.class.php
> +		$array['graphs'] = [$getRisksByDangerCategoriesAndCriticality, $getRisksByCotation , $getRisksByDangerCategories];
Si l'ordre est géré par la position, plus besoin de changer l'ordre dans l'array ?

2024-06-19 09:39 UTC, evarisk-micka commented on class/digiriskelement.class.php
> +            $array['data'] = array_count_values($children['all']);
Si jamais le "contient GP 6 UT 9" est fait dans une autre issue, penser à le retirer

2024-06-19 23:08 UTC, nicolas-eoxia requested changes
L'idée est très intéressante mais il faut revoir la conception car la position comme la visibilité est une donné configurable par l'utilisateur
De plus, on souhaite ici positionner les graphs par rapport au autre donc il s'agit d'une donnée du graph par de son chargement

2024-08-26 08:14 UTC, evarisk-micka requested changes
Issue à revoir, la position des graphiques devraient être géré par les utilisateurs et non défini impartialement

2024-08-26 14:36 UTC, evarisk-francois commented
Je vais poser ça ici parce que peut-être que je ne comprends pas bien le code et que je me complique la vie.
Actuellement la structure des graphiques est en dossier à peu près comme ça :

* type de donnée 1
  * graph 1
  * graph 2
* type de donnée 2
  * graph 1
* etc...

Le problème, c'est que quelle que soit la position des graphs, ils seront quand même bloqués par le type de donnée, e.g. même si un graph du type 2 est en position 1 et un graph du type 1 est en position 10, le graph de type 1 sera malgré tout affiché en premier.

Du coup, c'est compliqué de laisser le choix à l'utilisateur de l'ordre. Cependant, peut que de juste "flatten" la liste des graphs après les avoir récupérés serait la solution, sinon il faut revoir comment on récupère les graphs.

2025-08-01 14:48 UTC, closed without merging