#4026 [Mod] add: change labour doctor default name
Evarisk/Digirisk pull request #4039
Opened 2024-07-15 13:54 UTC by evarisk-francois

2024-07-26 12:21 UTC, nicolas-eoxia requested changes

2024-07-26 12:21 UTC, nicolas-eoxia commented on langs/fr_FR/digiriskdolibarr.lang
Structure fichier pas respecté

2024-07-26 12:21 UTC, nicolas-eoxia commented on core/modules/modDigiriskDolibarr.class.php
Psr12 pas respecter / $conf global déprécier / tms inutile/ status doit pas être un chiffre / trans déprécier sur insert bdd / 

Societe update vraiment pas opti ici 

Erreur de logique sur la fin de la condition

2024-08-20 10:12 UTC, evarisk-micka approved these changes

2024-08-26 08:16 UTC, evarisk-micka commented on core/modules/modDigiriskDolibarr.class.php
SaturneSchedule n'a pas de const pour le status, donc c'est toujours 1 par défaut (on pourrait le retirer mais il n'est pas défini par défaut dans la classe)

2024-08-26 08:18 UTC, evarisk-micka approved these changes

2025-08-01 14:51 UTC, merged