#3646 [Dashboard] add : Add download button for risk assessment document
Evarisk/Digirisk pull request #4071
Opened 2024-08-27 07:15 UTC by evarisk-kilyan

2024-08-27 07:18 UTC, evarisk-kilyan commented
Voir issue : https://github.com/Evarisk/Saturne/pull/1052

2024-08-27 07:54 UTC, evarisk-micka requested changes

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +        $dirFiles  = 'riskassessmentdocument';
PSR12

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +        require_once DOL_DOCUMENT_ROOT . '/core/lib/files.lib.php';
au dessus

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +            return "";
PSR12 => simple quote

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +        return '<a class="marginleftonly" href="' . $fileUrl . '" target="_blank">' . img_picto('download', $icon) . '</a>';
on ne return jamais de string complète tu dois la stocker dans une variable et améliorer la condition de retour

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +        $icon = $type == 'pdf' ? 'fa-file-pdf' : 'fa-file-alt';
un espace entre

2024-08-27 07:54 UTC, evarisk-micka commented on class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
> +            $documentUrl = $conf->global->DOL_URL_ROOT_DOCUMENT_PHP; // To use another wrapper
utilise à la place getDolGlobalString()

2024-08-28 11:42 UTC, nicolas-eoxia requested changes
Je comprend le concept proposé mais ça complexifie inutilement le code pour faire un widget 

Revoir avec moi pour la réalisation

2024-08-29 17:58 UTC, merged