#4086 [Cards] fix: use saturne for lock and archive
Evarisk/Digirisk pull request #4087
Opened 2024-09-13 07:30 UTC by evarisk-kilyan

2024-09-16 09:26 UTC, nicolas-eoxia approved these changes

2024-10-23 16:20 UTC, herveleni approved these changes
j'adore

2024-10-24 14:03 UTC, Muvikx approved these changes

2025-05-06 14:06 UTC, evarisk-micka commented
Deprecated, à reprendre quand saturneForm sera fini et il faudra ajouter les boutons manquants

2025-05-06 14:07 UTC, evarisk-micka requested changes
Deprecated, à reprendre quand saturneForm sera fini et il faudra ajouter les boutons manquants

2026-06-30 13:01 UTC, closed without merging